############################################
# APIリクエストサンプル集
#
############################################

@url = http://localhost:4001
#@url = https://


###ログイン(ユーザー認証)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "fugafuga@example.com", 
    "password": "fugafuga"
  }

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJNYXRlcmlhIiwiZW1haWwiOiJmdWdhZnVnYUBleGFtcGxlLmNvbSIsImV4cCI6MTU1Mjk3NTY0MSwiaWF0IjoxNTUyOTc1MDQxLCJpc3MiOiJNYXRlcmlhIiwianRpIjoiNWE0Yzg0NjQtYjQ1Yi00YmQ0LTg0OWItYzJiNmE1YmUzZDIwIiwibmJmIjoxNTUyOTc1MDQwLCJzdWIiOiJ7XCJ1c2VyX2lkXCI6Mn0iLCJ0eXAiOiJhY2Nlc3MifQ.W8mupoSTkzgaifAGDqduBByuq_j9fNoLSDvXTecLp1g

### 自分の直近limmit_count件のメッセージを取得

POST {{url}}/api/list-my-chat-message-recent HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "chat_room_id": 1,
    "limit_count": 30
}

###自分の最初のメッセージより以前の直近limmit_count件のメッセージを取得
POST {{url}}/api/list-my-chat-message-recent HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "chat_room_id": 1,
    "limit_count": 30,
    "first_message_id": 2
}

