############################################
# APIリクエストサンプル集
#
############################################

@url = http://localhost:4000
#@url = https://


###ログイン(ユーザー認証)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "fugafuga@example.com", 
    "password": "fugafuga"
  }


@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJNYXRlcmlhIiwiZW1haWwiOiJmdWdhZnVnYUBleGFtcGxlLmNvbSIsImV4cCI6MTU2NjM3MzEzOCwiaWF0IjoxNTY2MzcyNTM4LCJpc3MiOiJNYXRlcmlhIiwianRpIjoiMjJkOGVlMjgtNjhlMi00Yjg5LTlmMjUtODg2MmFmYTc2ZGJmIiwibmJmIjoxNTY2MzcyNTM3LCJzdWIiOiJ7XCJ1c2VyX2lkXCI6Mn0iLCJ0eXAiOiJhY2Nlc3MifQ.iQzT5a6b-g9FHr4zFOLohEq5aYhkdrUXHEMe3HJ6zvo

### 自分の直近limmit_count件のメッセージを取得

POST {{url}}/api/list-my-chat-message-recent HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "chat_room_id": 1,
    "limit_count": 30
}

###自分の最初のメッセージより以前の直近limmit_count件のメッセージを取得
POST {{url}}/api/list-my-chat-message-recent HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "chat_room_id": 1,
    "limit_count": 30,
    "first_message_id": 2
}

### 自分の未読メッセージ一覧を取得する
GET {{url}}/api/my-unread-messages HTTP/1.1
Content-Type: application/json
Authorization: {{token}}


